title: "NJ van As - DevOps & Cloud Architecture"
description: "Technical blog documenting homelab adventures, cloud certifications, and real-world problem-solving"
baseurl: "/Blog"
url: "https://njvanas.github.io"
author: "NJ van As"
email: "njvanas@duck.com"

# Build settings
markdown: kramdown
highlighter: rouge
theme: 
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# GitHub Pages specific settings
repository: njvanas/Blog
github_username: njvanas
linkedin_username: njvanas

# Navigation
header_pages:
  - about.md
  - archive.md

# SEO and social
twitter:
  username: njvanas
  card: summary

social:
  name: NJ van As
  links:
    - https://github.com/njvanas
    - https://linkedin.com/in/njvanas
    - https://njvanas.github.io

# Collections
collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Syntax highlighting
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true

# Show excerpts on home page
show_excerpts: true

# GitHub Pages safe mode
safe: true
incremental: false

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/